### ISSUE TITLE
Typos in english version.

### ISSUE THREAD

**Issue by Niquarl** [joinmisskey/joinmisskey.github.io#12]
* Misskey and other SNS connect each other because it exists in _the_ Fediverse (universe composed of various SNS.)

* 1 _post_ can contain 1000 characters

* You can configure _privacy_ range of your post finely

* You can determine a_n_ owner by your intention, or you can manage your own instance.

* If you want us to add instances to _the_ list

Just read the website. A few corrections to what I believe are typos or translation mistakes. Your SNS looks really nice :+1:

**Comment by tamaina** [comment]
Thanks a lot!
