### ISSUE TITLE
インスタンス容量の表示が気持ち悪い

### ISSUE THREAD

**Issue by tamaina** [joinmisskey/joinmisskey.github.io#8]
Misskeyのインスタンス容量はMBで設定される。  
インスタンス容量GB単位のインスタンスがあるが、`204800`のように2^10n的に設定しているところがある。  
numeral.jsで適当にディスプレイしているのだが、`204800`MBというのは`204.8GB`と表示され、なんだか気持ち悪い。ほんとうは`200.0GB`と表示したい。

と書いてみたはいいものの、良い解決策は思い浮かばない。  
2^10n的に設定しているところもあれば10^m的に設定しているところもあるので、単純に割ればいいというわけでもなさそう…

**Comment by CookieRamen** [comment]
あと、オブジェクトストレージを導入しているインスタンスでは容量の表示を消したほうがいい

**Comment by tamaina** [comment]
それはなぜですか？

**Comment by tamaina** [comment]
それと、一部のインスタンスの情報を消すならすべてのインスタンスの情報を消すことになりそう

**Comment by tamaina** [comment]
中途半端な表示でも別にいいか…
